#
# Please don't change this file unless you know what you are doing.
#
language: python
python:
  - "3.5"
# Install all the dependencies.
install: "pip install -r requirements.txt"
# Run tests.
script: "python emotly_tests.py"
