#
# Please don't change this file unless you know what you are doing.
#
language: python
python:
  - "3.5"

# Environment variables go here.:)
env:
  - EMOTLY_DB_URI=mongodb://localhost/dummydb EMOTLY_APP_SEC_SUPERSECRET=norealsecret

# Bind MongoDB.
services: mongodb

# Delay the build of few seconds to allow MongoDB
# to properly run and accept connections.
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

# Install all the dependencies.
install: "pip install -r requirements.txt"

# Run tests.
script: "python run_tests.py"

# Deploy.
deploy:
  provider: heroku
  app: emotly
  api_key:
    secure: pSKUQOiDrsTpk2zth+zTLd4jgirsrTDvzaC7DTz4k7k/ZzieezgDlTiwOtrBbE7ncrztIxqupsj+iZ3QxFTJGzM9z1GcHcVYBBSG5r6lTbgZEmpKq0tDC+H+sW8a1zlmBjOU7s61eClvrlRHaf6l8teUDzXOaLy/5lA/1kvzNZCNliXIjw0viDPZWkmnkkpH1tkKUtiVySa7Oa9gDPAXhnd7CBhy/SfoMQrh1zUHMcOfI+3yKt31q+k6TveWOa7XONZikx7TftRnJ6HSFogV5LMGB8Zgu+VXwOCuRpHIHUpsT+P3I1npiT1jIEHEXArvP2SvB2ZM27AchGYvm/j5O7kA32Py+V1HnliJq09OVirQnLAhpYUB9kpCoQFcUtNg020nA9WeKsHp7q1sd8zVqsWads4qEXXe2q2NouUsKN8KM60xmNfZ3W/c4j5lVBOhCe5YInXWV2CPeXra8vH5izzKy2YO0YTZFTjg9fWE07o7vuqTXgPlx8s7sW21K8TYLbeC9lRhKEIqw7LvD8zB2S0eIlAKUebYAOa1+c+7i8jnbAsdZTysRxRereQVflLnQGOnG1NdIX487msxhnn0rrOrhhcyomZRUh/srKwxpGb5b5a54dLl6rbr4+WW2B2oiereU+Mbb9HP7ATIZRnYoSH2Os9OvId8gdLFym6gM+I=
